project_id = "butjvqkzaxavgigxojfv"

[functions.generate-recipe]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false